# Application Properties
spring:
  application:
    name: pet
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
  devtools:
    restart:
      enabled: true

## Server Properties
server:
  port: 8080

app:
  jwtSecretKey: 'Ra7$3GP1).$5a@for4LpW&/ZWAt>i8UJC9X%b}lpD:GtYMcEt?PcMkh%,PLRL7$'
  jwtExpirationTime: 86400