# Application Properties
spring:
  application:
    name: pet
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
  devtools:
    restart:
      enabled: true

## Server Properties
server:
  port: 8080